// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/trial_1/dyDemoTrial_1/server/cmd/api/rpc"
)

func main() {
	rpc.InitRPC()
	h := server.Default(server.WithMaxRequestBodySize(20 << 20),
		server.WithHostPorts("0.0.0.0:8888"))

	register(h)
	h.Spin()
}
