// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/trial_1/dyDemoTrial_1/server/cmd/api/controller"
	"github.com/trial_1/dyDemoTrial_1/server/cmd/api/handlers"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	//r.GET("/ping", handler.Ping)

	// your code ...
	apiRouter := r.Group("/douyin")
	{
		//基础接口
		apiRouter.GET("/feed/", handlers.VideoFeed)
		apiRouter.GET("/user/", handlers.UserInfo)
		apiRouter.POST("/user/register/", handlers.UserRegister)
		apiRouter.POST("/user/login/", handlers.UserLogin)
		apiRouter.GET("/publish/list/", handlers.VideoPublishList)
		apiRouter.POST("/publish/action/", func(ctx context.Context, c *app.RequestContext) {
			println("开始运行")
			controller.Publish(ctx, c)
			println("/publish/action:post")
		})

		//互动接口
		apiRouter.POST("/favorite/action/", handlers.FavoriteAction)
		apiRouter.GET("/favorite/list/", handlers.FavoriteList)
		apiRouter.POST("/comment/action/", handlers.CommentAction)
		apiRouter.GET("/comment/list/", handlers.CommentList)

		//社交接口
		apiRouter.POST("/relation/action/", handlers.RelationAction)
		apiRouter.GET("/relation/follow/list/", handlers.FollowList)
		apiRouter.GET("/relation/follower/list/", handlers.FollowerList)
		apiRouter.GET("/relation/friend/list/", handlers.FriendList)
		apiRouter.POST("/message/action/", handlers.MessageAction)
		apiRouter.GET("/message/chat/", handlers.MessageChat)

	}

}
